// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeUFPUPS9orVb04dZfBGG_SjgsQn-FH3M',
    appId: '1:849090647277:web:400196f2d630c97e1d28e4',
    messagingSenderId: '849090647277',
    projectId: 'autism-gemastik',
    authDomain: 'autism-gemastik.firebaseapp.com',
    databaseURL: 'https://autism-gemastik-default-rtdb.firebaseio.com',
    storageBucket: 'autism-gemastik.appspot.com',
    measurementId: 'G-6SMXSZ4VMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHlyvmiwPQqbaIXEHvw12LzNoIhtuHtEY',
    appId: '1:849090647277:android:4d99c632cbed32b01d28e4',
    messagingSenderId: '849090647277',
    projectId: 'autism-gemastik',
    databaseURL: 'https://autism-gemastik-default-rtdb.firebaseio.com',
    storageBucket: 'autism-gemastik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMlLWhUQlQ2ylxbo5ncXi8Q6O-zeDfJVI',
    appId: '1:849090647277:ios:4542927a5b2c12d51d28e4',
    messagingSenderId: '849090647277',
    projectId: 'autism-gemastik',
    databaseURL: 'https://autism-gemastik-default-rtdb.firebaseio.com',
    storageBucket: 'autism-gemastik.appspot.com',
    iosClientId: '849090647277-4i61cgbh312iiqtj9bj5gpm113unejma.apps.googleusercontent.com',
    iosBundleId: 'com.aksonhealthp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMlLWhUQlQ2ylxbo5ncXi8Q6O-zeDfJVI',
    appId: '1:849090647277:ios:4542927a5b2c12d51d28e4',
    messagingSenderId: '849090647277',
    projectId: 'autism-gemastik',
    databaseURL: 'https://autism-gemastik-default-rtdb.firebaseio.com',
    storageBucket: 'autism-gemastik.appspot.com',
    iosClientId: '849090647277-4i61cgbh312iiqtj9bj5gpm113unejma.apps.googleusercontent.com',
    iosBundleId: 'com.aksonhealthp',
  );
}
